# Generated by Django 5.2.13 on 2026-05-14 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
